### ISSUE TITLE
Write tests for issues from 18.4 softfork 

### ISSUE THREAD

**Issue by AKorpusenko** [GolosChain/Qa#12]
# Description :red_circle: 
As new release of Golos blockchain is comming, we need to cover done issues with the tests.

# Issues :red_circle: 
Following issue have to covered with the tests:
- [ ] [794](https://github.com/GolosChain/golos/issues/794) Configuration flag for storing account metadata
- [ ] [796](https://github.com/GolosChain/golos/issues/796) Add depth history for storing comment contents
- [ ] [801](https://github.com/GolosChain/golos/issues/801) Refactor clear_votes() to history depth. [PR 897](https://github.com/GolosChain/golos/issues/897)
- [ ] [797](https://github.com/GolosChain/golos/issues/797) Add flag for storing memo in transfer from saving

**Comment by AKorpusenko** [comment]
@maslenitsa93 , to test 797, 828, 829 issues we need to write simple MongoDB wrapper for test system to finish tests for `config_tests`. As I see in you checklists in pull-requests, there are complete code for tests. As it is much more clear how to test via `cli_wallet` than using golos-js, we can also add possible to run `cli_wallet` scripts, just like bash scripts.

Making two more issues for that. :hammer:
